# Generated by Django 2.1 on 2019-07-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bool',
            new_name='body',
        ),
    ]
